# Generated by Django 4.1.2 on 2022-11-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('area', models.CharField(max_length=150, verbose_name='Área')),
                ('state', models.CharField(choices=[('Aprobado', 'aprobado'), ('Pendiente', 'pendiente'), ('Finalizado', 'finalizado')], max_length=10, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('fundamentation', models.TextField(verbose_name='Fundamentación')),
                ('evaluation', models.TextField(verbose_name='Evaluación')),
                ('conclution', models.TextField(verbose_name='Conclución')),
                ('recomendation', models.TextField(verbose_name='Recomendación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/projects/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'Project',
            },
        ),
    ]
