# Generated by Django 4.1.2 on 2022-11-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectProcesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('number_phone', models.CharField(max_length=8, unique=True, verbose_name='Teléfono movil')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('area', models.CharField(max_length=150, verbose_name='Área')),
                ('position', models.CharField(max_length=150, verbose_name='Cargo')),
                ('projects', models.ManyToManyField(to='ProjectProcesses.project')),
            ],
        ),
    ]
