# Generated by Django 4.1.2 on 2022-11-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitie_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descriptions', models.TextField(verbose_name='Descripción')),
                ('realization_date', models.DateField(verbose_name='Fecha de realización')),
                ('count_persons', models.SmallIntegerField(default=0, verbose_name='Cantidad de personas')),
            ],
            options={
                'verbose_name': 'Activitie',
                'verbose_name_plural': 'Activities',
                'db_table': 'Activitie',
            },
        ),
    ]
